"""Replace speculative acceleration material with measured pipeline-only conclusions."""
import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];path=ROOT/'camera pose消融试验记录报告.md';out=ROOT/'results/lerobot_pipeline_ab'
base=path.read_text().split('## 四、')[0].split('### 3.4')[0]
p=out/'summary.json';s=json.loads(p.read_text()) if p.exists() else None
conclusion='4. **正在对固定2048条视频做串行/流水线对照。** 保持模型、4fps/240/36、预处理和BOS回读校验不变，以实际完成耗时评价收益。'
extra=[]
if s:
 a=s['phases']['serial'];b=s['phases']['pipeline'];audit=s['audit'];conclusion=f"4. **同一2048条视频的流水线实测加速{s['speedup']:.2f}倍，墙钟减少{s['wall_time_reduction_fraction']*100:.1f}%。** 八卡日吞吐由{a['video_hours_per_machine_day']:.0f}提升至{b['video_hours_per_machine_day']:.0f}小时，平均每卡折算{b['video_hours_per_gpu_day_average']:.0f}小时/天；这是固定样本单次对照外推。"
 extra=['### 3.4 同一2048条视频：流水线掩盖实测','',f"采用此前随机清单前2048条，两个阶段各完整处理一次，共{a['video_s']/3600:.3f}小时原视频。八个模型加载及预热后常驻，先串行后流水线，使用同一模型进程、同一输入集合、相同4fps/240/36和BOS回读校验。",'', '| 项目 | 串行基线 | 解码/上传流水线 |','|---|---:|---:|',f"| 完成视频 | {a['videos']} | {b['videos']} |",f"| 总墙钟/s | {a['wall_s']:.2f} | {b['wall_s']:.2f} |",f"| 八卡外推视频小时/天 | {a['video_hours_per_machine_day']:.1f} | {b['video_hours_per_machine_day']:.1f} |",f"| 平均每卡折算小时/天 | {a['video_hours_per_gpu_day_average']:.1f} | {b['video_hours_per_gpu_day_average']:.1f} |",f"| 推理路径累计worker秒 | {a['inference_worker_s']:.2f} | {b['inference_worker_s']:.2f} |",f"| BOS传输/校验累计worker秒 | {a['upload_worker_s']:.2f} | {b['upload_worker_s']:.2f} |",f"| 单worker峰值allocated/GiB | {a['peak_worker_allocated_gib']:.2f} | {b['peak_worker_allocated_gib']:.2f} |",f"| 重试过的任务数 | {a['attempts_over_one']} | {b['attempts_over_one']} |",'', f"总完成加速比 = {a['wall_s']:.2f}/{b['wall_s']:.2f} = {s['speedup']:.3f}。总时间减少{s['wall_time_reduction_fraction']*100:.2f}%。上传仍然执行，本次改动是各阶段重叠，没有省略上传或回读；推理路径计时本身也可能随CPU调度及GPU运行状态变化，不把全部差值归因于某一个等待环节。",f"对{audit['checked_npz_pairs']}对输出逐数组校验，其中{audit['bitwise_equal_npz_arrays']}对所有NPZ数组逐位一致；c2w最大绝对差{audit['max_pose_abs_difference']:.3g}，内参最大绝对差{audit['max_intrinsics_abs_difference']:.3g}。共{audit['BOS_readback_verified_files']}个NPZ/JSON通过BOS回读SHA256核对。",'', '本组采用完整固定集合的总完成时间，包含填充/排空、最后长片段以及最后一次BOS确认；不能把1771条/固定600秒的旧口径直接当成这次串行对照。两个阶段为单次顺序运行，没有置信区间；操作系统/文件系统缓存未强制清空，也不代表冷缓存。', '模型启动不计入总墙钟；八卡阶段吞吐按“相同原视频秒数÷实际完成墙钟×24”计算，平均每卡为整机除以8。流水线存在多个任务并行排队，单任务延迟可能上升，不能用其任务耗时之和代替整机墙钟。', '', '![固定样本流水线对照](results/lerobot_pipeline_ab/comparison.png)', '', '原始证据：[固定样本协议](results/lerobot_pipeline_ab/PROTOCOL.md)、[汇总JSON](results/lerobot_pipeline_ab/summary.json)、[逐视频配对CSV](results/lerobot_pipeline_ab/paired.csv)、[数值与BOS审计](results/lerobot_pipeline_ab/artifact_audit.json)。','']
base=base.replace('3. **当前八卡整机外推','3. **流水线改造前的早期八卡基线外推')
base=re.sub(r'^4\. \*\*.*$',lambda _:conclusion,base,flags=re.M)
recommend=['## 四、建议','', '### 4.1 生产配置','', '继续使用Ω、4fps、240帧窗口、36帧overlap、步长204帧。精度优先的快速运动片段可以单独采用8fps，但不要把这种采样率变化混入流水线加速收益。', '', '### 4.2 已实现的流水线','', '每张卡仍只有一个常驻模型，推理仍逐视频/窗口独立执行。流水线顺序为：任务领取→CPU解码/预处理→有界窗口队列→GPU推理→CPU拼接和写出→异步BOS上传/回读→server完成确认。', '每GPU配置：1个解码生产线程、最多2个待推理窗口、1个GPU推理消费者、2个BOS上传线程，最多4个已领取任务在途。图像流式处理，单窗口最多240帧；另有生产和消费缓冲，不能把“队列2”理解成整个进程最多两份窗口。', '解码下一条视频或下一个窗口时，GPU可以计算当前窗口；前一条视频的上传和回读可与后续GPU计算重叠。CPU拼接和文件初次保存目前仍在GPU消费者线程执行，因为旧基线中它们占比很小。', '保留原有H2D同步和逐视频empty_cache，避免把额外显存/拷贝改动混入本次对照。模型权重、图像缩放、轨迹拼接和校验强度都未改变。', '', '### 4.3 可靠性与容量','', '所有在途任务从领取到BOS回读完成持续续租；上传成功且校验通过前，不向server标记done。短暂传输错误先重试现有文件，最终失败保留记录和本地产物。按任务/lease使用独立输出目录，防止旧任务覆盖新结果。', '有界队列用于防止GPU或BOS变慢时堆积整段视频，占用过多CPU内存。后续提高解码或上传并发时，应同时观察CPU/RAM、队列等待和整个八卡吞吐，不能只看显存是否空闲。', '', '### 4.4 后续仅针对流水线的调优','', '可继续比较预取队列深度1/2/4、解码线程数、上传线程数和allocator缓存复用；对pinned host memory、异步H2D与独立copy stream的改动应另做同口径对照。当前实测未包含这些额外优化，不据此预报新的加速倍数。', 'BOS逐条回读校验目前保留。若未来改成抽样回读或调整对象打包方式，需要明确记录校验口径变化，不能把减少校验开销算成当前流水线的同口径收益。', '', '### 4.5 代码、服务与报告复现','', '入口：[process_camera_lerobot.py](process_camera_lerobot.py)，增加`client --pipeline`启用流水线；实现：[lerobot_pipeline.py](scripts/lerobot_pipeline.py)。部署和恢复说明：[PROCESS_CAMERA_LEROBOT.md](PROCESS_CAMERA_LEROBOT.md)。', '对照驱动：[benchmark_lerobot_pipeline_ab.py](scripts/benchmark_lerobot_pipeline_ab.py)；统计和校验：[report_lerobot_pipeline_ab.py](scripts/report_lerobot_pipeline_ab.py)。原始NPZ仍为OpenCV c2w、首帧原点、任意平移尺度，未覆盖LeRobot原始parquet。', '本次对照BOS前缀：`/mnt/bos/liberai-web-humandata/processing/for_next_20260901_150304_249934232/temp_camera_motion/pipeline_ab_20260909/`，分别使用serial与pipeline子目录。此前八卡吞吐证据仍保存在`benchmark_20260909_8gpu_4fps_ov36/`。']
text=base+'\n'.join(extra+recommend)+'\n'
assert 'batch' not in text.lower(), 'Unexpected batch discussion'
path.write_text(text);print(path)
